server {
    listen 80;
    server_name _;

    # 1. SERVE STATIC FILES
    location /media/ {
        # Inside the container, we will map the files to this path
        alias /var/www/media/;
        autoindex off; # Security: prevent listing files
    }

    # 2. PROXY TO HASKELL API
    # Any request NOT for media goes to the backend
    location / {
        # Use the Docker Service Name and INTERNAL port
        proxy_pass http://tkani-api-container:8080;
        
        # Standard proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}