name:                tkani-api
version:             0.1.0.0
# ... other fields ...

dependencies:
  - base >= 4.18 && < 5

library:
  source-dirs: src
  exposed-modules:
    - API
    - API.Types
    - Handlers
    - App
    - Config
    - Infrastructure.Logging.Telegram
    - Infrastructure.Templating
    - Workers.SdekOrderStatusPoller
    - Workers.TinkoffPaymentStatusPoller
  dependencies:
    # This list should already be complete
    - aeson
    - async
    - async-extra
    - bytestring
    - containers
    - hasql
    - hasql-pool
    - hasql-th
    - hasql-transaction
    - http-api-data
    - katip
    - mtl
    - lens
    - profunctors
    - servant
    - servant-server
    - stm
    - template-haskell
    - text
    - transformers
    - tuple-sop
    - wai
    - warp
    - wreq
    - unix
    - http-client
    - http-client-tls 
    - exceptions
    - http-types
    - time
    - random
    - vector
    - monad-time
    - unordered-containers
    - directory
    - filepath
    - lifted-async
    - monad-control
    - transformers-base
    - uuid
    - lifted-base

executables:
  tkani-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      # This is the section to update.

      # It depends on our own library
      - tkani-api

      # It directly uses these packages in Main.hs
      - async
      - lifted-async
      - mtl
      - servant
      - servant-server
      - warp
      - wai
      - wai-cors
      - stm
      - text
      - yaml
      - tuple-sop
      - exceptions
      - http-client
      - http-client-tls
      - unordered-containers
      - containers   

      # --- ADD THESE LINES ---
      - katip             # For initLogEnv, closeScribes
      - hasql
      - hasql-pool        # For acquire, release