{-# LANGUAGE OverloadedStrings #-}

module Infrastructure.Services.Tinkoff (initiateTinkoffPayment, module Types) where

import Data.Text (Text)

import App (AppM)
import Infrastructure.Services.Tinkoff.Types as Types



-- | Initializes a payment session with the Tinkoff Acquiring API (`Init` method). 
--   https://developer.tbank.ru/eacq/api/init
--
-- This function is the first step in the payment process. It's a critical,
-- synchronous step in the user-facing order creation flow. The bot calls this
-- function and waits for the result before responding to the user.
--
-- The process is as follows:
--
--   1. Constructs a JSON payload with the order amount, our internal Order ID,
--      and other necessary details.
--   2. Generates a secure `Token` by creating a SHA-256 hash of the payload
--      parameters combined with the secret terminal password.
--   3. Sends a POST request to the Tinkoff `Init` endpoint.
--   4. Parses the JSON response to extract the Payment URL and Payment ID.
--
-- @param orderDetails A record containing information about the order,
--        such as 'orderId' and 'amountKopecks'.
-- @return An `Either` containing an `ApiError` on failure, or a tuple of
--         (`paymentUrl`, `paymentId`) on success.
--
-- == Caller Responsibilities
--
-- The function that calls this is responsible for:
--
--   - __SAVING__ the returned `paymentId` to the database and associating it
--     with the order. This ID is essential for the background polling worker.
--   - __SENDING__ the returned `paymentUrl` back to the user via the bot,
--     so they can click the link and pay.
initiateTinkoffPayment
  :: OrderDetails                      -- ^ Details of the order to create a payment for.
  -> AppM (Either ApiError (Text, Text))  -- ^ A tuple of (`paymentUrl`, `paymentId`), or an error.
initiateTinkoffPayment orderDetails = do
  -- ... function implementation goes here ...
  return $ Right ("https://google.com", "1232")


-- | Queries the Tinkoff Acquiring API to get the current status of a payment (`GetState` method).
--  https://developer.tbank.ru/eacq/api/get-state
--
-- This function is the core of the payment polling worker. It is designed to
-- be called periodically in a background job for orders that are in an
-- 'AWAITING_PAYMENT' state. It does NOT interact with the user directly.
--
-- The process is as follows:
--
--   1. Constructs a minimal JSON payload containing the `PaymentId` to check.
--   2. Generates the required security `Token` for the `GetState` request.
--   3. Sends a POST request to the Tinkoff `GetState` endpoint.
--   4. Parses the JSON response and extracts the `Status` field.
--
-- @param paymentId The unique `PaymentId` that was generated by the `Init`
--        call and stored in our database.
-- @return An `Either` containing an `ApiError` on failure, or the status
--         string from Tinkoff (e.g., "CONFIRMED", "REJECTED") on success.
--
-- == Usage by the Polling Worker
--
-- The background poller that calls this function is responsible for analyzing
-- the returned status string and taking the following actions:
--
--   - `Right "CONFIRMED"`: Update the order status in the DB to 'PAID' and
--     trigger a success notification to the user.
--   - `Right "REJECTED"`, `Right "CANCELED"`, `Right "DEADLINE_EXPIRED"`: Update the order
--     status in the DB and potentially notify the user of the failure.
--   - `Right "NEW"`, `Right "PROCESSING"`: Take no action and check again later.
--   - `Left apiError`: Log the error, as the check failed at a network/parsing level.
checkTinkoffPaymentStatus
  :: Text                                 -- ^ The `PaymentId` to query the status for.
  -> AppM (Either ApiError Status)          -- ^ The status string from the API, or an error.
checkTinkoffPaymentStatus paymentId = do
  -- ... function implementation goes here ...
  return $ Right New