{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TemplateHaskell #-}

module Infrastructure.Services.Tinkoff 
       ( initiateTinkoffPayment
       , checkTinkoffPaymentStatus
       , getTinkoffQRCode
       , cancelTinkoffPayment
       , initiateTinkoffRubleTransfer
       ) where

import Data.Text (Text, unpack, pack)
import Control.Monad.Reader.Class (ask)
import Data.Bifunctor (second)
import Katip
import Data.Traversable (for)
import Data.Maybe (fromMaybe)
import Control.Monad.IO.Class (liftIO)

import App (AppM, _tinkoffCred, _configHttpManager, _tinkoffOpenApiManager, tinkoffOpenApiUrl, tinkoffUrl, Scheme (HTTPS))
import Infrastructure.Services.Tinkoff.Types.Init
import Infrastructure.Services.Tinkoff.Security (generatedInitToken, InitToken(..))
import Infrastructure.Utils.Http (postReq, HttpError)
import Infrastructure.Services.Tinkoff.Types.GetState (Status (..), GetStateRequest, GetStateResponse (..))
import Infrastructure.Services.Tinkoff.Types.QR
import Infrastructure.Services.Tinkoff.Types.Cancel
import Infrastructure.Services.Tinkoff.Types.RubleTransfer



-- | Initializes a payment session with the Tinkoff Acquiring API (`Init` method). 
--   https://developer.tbank.ru/eacq/api/init
--
-- This function is the first step in the payment process. It's a critical,
-- synchronous step in the user-facing order creation flow. The bot calls this
-- function and waits for the result before responding to the user.
--
-- The process is as follows:
--
--   1. Constructs a JSON payload with the order amount, our internal Order ID,
--      and other necessary details.
--   2. Generates a secure `Token` by creating a SHA-256 hash of the payload
--      parameters combined with the secret terminal password.
--   3. Sends a POST request to the Tinkoff `Init` endpoint.
--   4. Parses the JSON response to extract the Payment URL and Payment ID.
--
-- @param orderDetails A record containing information about the order,
--        such as 'orderId' and 'amountKopecks'.
-- @return An `Either` containing an `ApiError` on failure, or a tuple of
--         (`paymentUrl`, `paymentId`) on success.
--
-- == Caller Responsibilities
--
-- The function that calls this is responsible for:
--
--   - __SAVING__ the returned `paymentId` to the database and associating it
--     with the order. This ID is essential for the background polling worker.
--   - __SENDING__ the returned `paymentUrl` back to the user via the bot,
--     so they can click the link and pay.
initiateTinkoffPayment
  :: InitRequest                      -- ^ Details of the order to create a payment for.
  -> AppM (Either HttpError InitResponse)  -- ^ A tuple of (`paymentUrl`, `paymentId`), or an error.
initiateTinkoffPayment initReq = do
  -- ... function implementation goes here ...
  cfg <- ask
  let url = tinkoffUrl $ _tinkoffCred cfg
  let httpManager = _configHttpManager cfg
  postReq @InitResponse httpManager (show HTTPS <> unpack url <> "/v2/Init") initReq [] Nothing


-- | Queries the Tinkoff Acquiring API to get the current status of a payment (`GetState` method).
--  https://developer.tbank.ru/eacq/api/get-state
--
-- This function is the core of the payment polling worker. It is designed to
-- be called periodically in a background job for orders that are in an
-- 'AWAITING_PAYMENT' state. It does NOT interact with the user directly.
--
-- The process is as follows:
--
--   1. Constructs a minimal JSON payload containing the `PaymentId` to check.
--   2. Generates the required security `Token` for the `GetState` request.
--   3. Sends a POST request to the Tinkoff `GetState` endpoint.
--   4. Parses the JSON response and extracts the `Status` field.
--
-- @param paymentId The unique `PaymentId` that was generated by the `Init`
--        call and stored in our database.
-- @return An `Either` containing an `ApiError` on failure, or the status
--         string from Tinkoff (e.g., "CONFIRMED", "REJECTED") on success.
--
-- == Usage by the Polling Worker
--
-- The background poller that calls this function is responsible for analyzing
-- the returned status string and taking the following actions:
--
--   - `Right "CONFIRMED"`: Update the order status in the DB to 'PAID' and
--     trigger a success notification to the user.
--   - `Right "REJECTED"`, `Right "CANCELED"`, `Right "DEADLINE_EXPIRED"`: Update the order
--     status in the DB and potentially notify the user of the failure.
--   - `Right "NEW"`, `Right "PROCESSING"`: Take no action and check again later.
--   - `Left apiError`: Log the error, as the check failed at a network/parsing level.
checkTinkoffPaymentStatus
  :: GetStateRequest                         -- ^ The get state request containing the `paymentId` to check.
  -> AppM (Either HttpError Status)          -- ^ The status string from the API, or an error.
checkTinkoffPaymentStatus getStateReq = do
  -- ... function implementation goes here ...
  cfg <- ask
  let url = tinkoffUrl $ _tinkoffCred cfg
  let httpManager = _configHttpManager cfg
  eResp <- postReq @GetStateResponse httpManager (show HTTPS <> unpack url <> "/v2/GetState") getStateReq [] Nothing
  $(logTM) InfoS $ ls $ "Tinkoff GetState response: " <> pack (show eResp)
  for eResp $ \resp -> do 
    let isSuccess = gsrpSuccess resp
    if not isSuccess
    then
      let errCode = maybe "Unknown error" id (gsrpErrorCode resp) in
      error $ "Tinkoff GetState API call failed with error code: " <> unpack errCode
    else return $ fromMaybe undefined $ gsrpStatus resp

  
-- | Makes a request to the T-Bank '/v2/GetQr' endpoint to generate a payment QR code. 
--   https://developer.tbank.ru/eacq/api/get-qr
--
-- This function is called immediately after a successful 'Init' request. It takes the
-- 'PaymentId' from the initial session and requests the corresponding QR data from
-- Tinkoff for payment via SBP (Faster Payments System).
--
-- The function handles the necessary authentication by generating a specific 'Token'
-- signature for the GetQr request. The signature is composed of the 'PaymentId',
-- 'TerminalKey', and the terminal's secret password.
--
-- __Workflow:__
--
-- 1. Construct a 'GetQrRequest' with the 'PaymentId' from a previous 'Init' call.
-- 2. This function is called with the request object.
-- 3. It makes a POST request to the '/v2/GetQr' endpoint.
-- 4. On success, it returns a 'Right GetQrResponse' containing either:
--    - A URL payload (`DataType = PAYLOAD`).
--    - An SVG image string (`DataType = IMAGE`).
-- 5. On failure (network error, invalid token, etc.), it returns a 'Left HttpError'.
--
-- The returned SVG or payload can then be sent to the user in the Telegram bot
-- to complete the payment.
--
-- @param qrReq The 'GetQrRequest' data transfer object containing the 'PaymentId',
--              'TerminalKey', desired 'DataType', and the pre-computed 'Token'.
-- @return An 'Either HttpError GetQrResponse' representing the outcome of the API call.
getTinkoffQRCode
  :: GetQrRequest
  -> AppM (Either HttpError GetQrResponse)
getTinkoffQRCode qrReq = do
  cfg <- ask
  let url = tinkoffUrl $ _tinkoffCred cfg
  let httpManager = _configHttpManager cfg
  liftIO $ print $ "qr url -> " <> (show HTTPS <> unpack url <> "/v2/GetQr")
  postReq @GetQrResponse httpManager (show HTTPS <> unpack url <> "/v2/GetQr") qrReq [] Nothing


{-|
Performs a request to the Tinkoff Acquiring 'Cancel' endpoint to reverse a payment.

This function constructs the JSON payload from the provided 'CancelRequest' record,
sends it to the /v2/Cancel endpoint, and attempts to parse the JSON response
into a 'CancelResponse'. It handles network errors and decoding failures gracefully.

@see https://securepay.tinkoff.ru/v2/Cancel

@param cancelReq The request body payload ('CancelRequest'). This record should
                 contain all the necessary fields required by the Tinkoff API,
                 such as the 'PaymentId' of the transaction to be cancelled
                 and a security 'Token'.

@return An 'AppM' action that results in an 'Either'.
        - 'Right CancelResponse' on a successful API call where the response
          body was successfully parsed. This response typically includes the
          final 'Status' of the transaction (e.g., "CANCELED").
        - 'Left HttpError' on failure. This can represent a network error
          (e.g., timeout), a non-2xx HTTP status code from Tinkoff, or a
          JSON decoding error if the response is malformed.
-}
cancelTinkoffPayment
  :: CancelRequest
  -> AppM (Either HttpError CancelResponse)
cancelTinkoffPayment cancelReq = do
  cfg <- ask
  let url = tinkoffUrl $ _tinkoffCred cfg
  let httpManager = _configHttpManager cfg
  postReq @CancelResponse httpManager (show HTTPS <> unpack url <> "/v2/Cancel") cancelReq [] Nothing



-- https://developer.tbank.ru/docs/api/payments-core-pay
initiateTinkoffRubleTransfer :: RubleTransferRequest -> AppM (Either HttpError RubleTransferResponse)
initiateTinkoffRubleTransfer req = do
  cfg <- ask
  let url = tinkoffOpenApiUrl $ _tinkoffCred cfg
  let httpManager = _tinkoffOpenApiManager cfg
  let path = "/api/v1/payment/ruble-transfer/pay"
  postReq @RubleTransferResponse httpManager (show HTTPS <> unpack url <> path) req [] Nothing