# In your main config file

# ... other settings like database, server_port, etc.

# Base URL for the SDEK API (can be test or prod)
#  prod: "api.cdek.ru"
url: "api.edu.cdek.ru"

# Your API credentials for authentication
credentials:
  client_id: "YOUR_SDEK_CLIENT_ID"
  client_secret: "YOUR_SDEK_CLIENT_SECRET"


# drop_off_point: MSK2184
# drop_off_point: MSK2184
drop_off_point: MSK65

courier_drop_off_point: MSK339
# courier_drop_off_point: MSK65

# Your default tariff codes for different delivery types
tariffs:
  # Courier pickup -> Customer pickup at PVZ (Door-to-Warehouse)
  - 234
  - 136

# Your standard daily window for courier pickup requests
pickup_window:
  from: "13:00"
  to: "15:00"

consolidation_time: 21


# Business account number for reference
account_number: "YOUR_SDEK_ACCOUNT_NUMBER"

sender:
  name: "Sergey Yakovlev"
  phone: "+79361645867"
  email: "fclaw007@gmail.com"

# Minimum order amount for courier pickup
pickup_parcels: 5
pickup_weight: 5000

# 3 %
commission_rate: 1.035

# Details about your office for courier pickup (from_location)
sender_location:
  # Full, detailed address for the courier. YES, include floor/office.
  address: "г. Москва, шоссе Энтузиастов, 56с32, этаж 3, офис 361"
  
  # SDEK's internal numeric code for the city (44 for Moscow)
  city_code: 44
  
  # Postal code is often mandatory
  postal_code: "111123"

holidays:
  - month: 2
    day: 23
  - month: 3
    day: 8
  - month: 3
    day: 7
  - month: 3
    day: 9