

api_key: y2_AgAAAAD04omrAAAPeAAAAAACRpC94Qk6Z5rUTgOcTgYFECJllXYKFx8

api_url: "b2b.taxi.tst.yandex.net"

office:
 latitude: 55.759937
 longitude: 37.763681

local_warehouse_id: "tkani_msk"

warehouse_name: "Tkani MSK"

address: 
  city: "Москва"
  house: "56"
  building: "32"
  floor: "3"
  street: "шоссе Энтузиастов"

contact:
  name: "Sergey"
  surname: "Yakovlev"
  phone: "+79361645867"
  email: "fclaw007@gmail.com"

warehouse_postfix: "LOCAL"

pickup_parcels: 1
pickup_weight: 5000

pickup_window:
  from_hour: "13:00"
  to_hour: "15:00"